---
title: "Migrating my blog from `fastpages` to `Quarto`"
description-meta: "Migrating my blog from `fastpages` to Quarto"
date: 2023-07-17
toc: true
categories: [meta, quarto]
format: html
draft: false
image: "https://source.unsplash.com/npxXWgQ33ZQ"
---

# The Benefits of Project Quarto for Python Development Bloggers

Are you a Python development blogger searching for an efficient and effective way to publish your blog posts? Look no further than the Quarto project!

## What is Project Quarto?

Quarto is an open-source, web-based platform designed to simplify the creation and publication of scientific documents, including data-driven reports, technical articles, and more. With an easy-to-use interface and a wide range of customizable features, Quarto makes it simple to publish your Python development blogs.

## Why and When Developers Should Use Quarto?

Developers should use Quarto when searching for a cost-effective and customizable way to publish their blog posts. The Quarto project simplifies the process of organizing, formatting, and publishing scientific documents, with features such as:

- Compatibility with a wide range of programming languages, including R, Python, and Julia;
- Integration with popular web publishing platforms such as GitHub pages and Jekyll;
- Support for a broad range of document outputs, including LaTeX, PDF, and HTML;
- Extensive customizability with built-in templates and reusable components; and
- Built-in support for code snippets and data visualizations.

With its comprehensive range of features and user-friendly interface, Quarto is an ideal choice for Python developers looking for a streamlined and customizable approach to blogging.

## Quarto is the Future: The Discontinuation of Fastpages

While Fastpages was once a popular option for Python development bloggers, development of that platform has officially been discontinued. With its wide-ranging limitations and lack of further support, Fastpages is no longer a viable option for many Python development bloggers.

As an alternative, the Quarto project offers a robust platform for scientific document publication that is both customizable and user-friendly. The platform is designed with metadata-driven management and robust document-related capabilities for modern scientists and data professionals.



## Installing Quarto

Go to the [get started](https://quarto.org/docs/get-started/) page on the quarto website to download the installer file. I’m on Ubuntu, so for me that’s a .deb file. I install it from the command line:

```bash
sudo dpkg -i quarto-1.3.433-linux-amd64.deb

```

Create my blog project, called `quarto-blog`:

```bash
quarto create-project quarto-blog --type website:blog

```
then enter the project and preview it:

```bash
cd quarto-blog/
quarto preview quarto-blog
```

::: {.callout-important}
TODO: Add screenshot to preview here
:::

## Migrating fastpages's posts to Quarto

## Setup `favicon`

## Adding `canonical` tag into the `<head>` section

## Git/Github

before

:::{.column-margin}
This is a side comment/text/note and can support any markdown syntax!
:::

after
### Setup github pages

[Follow this](https://quarto.org/docs/publishing/github-pages.html).

### Add custom domain to github pages

First remove the domain in repository [fastpages-blog](https://github.com/xboard/fastpages-blog)

then add domain to [quarto-blog] repository.

## Creating Conda's environment


## Setup `posts/_metadata.yml`

### Setup (giscus)[https://giscus.app/] comments


## Adding dark mode 


## Adding google anaytics and RSS


## Setup footer

## VSCode

### Adding Quarto extesion

### Adding snippet

### Enabling inline suggestion
Set `Snippet suggestions` to `inline` as recommended [here](https://stackoverflow.com/a/74339599/483157).

## Conclusion

If you're a Python developer looking for an efficient, cost-effective, and customizable way to publish your Python development blog, the Quarto project is an excellent choice. With integrated features such as metadata
