project:
  type: website

website:
  title: "xboard.dev"
  site-url: https://xboard.dev
  description: "Everything data and programming."
  google-analytics: "G-5FL5R0TTQ6"
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xboard
      - icon: twitter
        href: https://twitter.com/xboard_
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css


theme:
  light: flatly
  dark: darkly