project:
  type: website

website:
  title: "xboard.dev"
  favicon: favicon.ico
  site-url: https://xboard.dev
  description: "Everything data and programming."
  google-analytics: "G-5FL5R0TTQ6"
  twitter-card:
    creator: "@xboard_"
    card-style: summary_large_image
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xboard
      - icon: twitter
        href: https://twitter.com/xboard_
      - icon: rss
        href: index.xml
  page-footer:
    center: |
      Made with Data, ❤️, 🐍 and [Quarto](https://quarto.org). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/).
  comments:
    giscus:
      repo: xboard/quarto-blog
      repo-id: R_kgDOJ7r2SQ
      category: Announcements
      category-id: DIC_kwDOJ7r2Sc4CX95f
      loading: lazy

format:
  html:
    smooth-scroll: true
    theme: 
      light: litera
      dark: superhero
    css: styles.css

theme:
  light: flatly
  dark: darkly

