project:
  type: website

website:
  title: "xboard.dev"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xboard
      - icon: twitter
        href: https://twitter.com/xboard_
format:
  html:
    theme: cosmo
    css: styles.css



